### ISSUE TITLE
android runtime not found

### ISSUE THREAD

**Issue by ryanramage** [holepunchto/bare-runtime#3]
trying on android via termux, npm install works fine, but running bare, I get

'no binary found for target android-arm64`

**Comment by mafintosh** [comment]
ah! we'll fix next week

**Comment by kasperisager** [comment]
@ryanramage Android builds are out in v1.0.2. They're produced by https://github.com/holepunchto/bare/blob/main/.github/workflows/prebuild.yml in case you'd like to inspect the build configuration.

Do let me know if there are any issues with the builds!
